### ISSUE TITLE
Feature Request: Python 3 Support

### ISSUE THREAD

**Issue by astromme** [jdillworth/pycedict#1]
Does this work with Python 3?
I installed pycedict with `pip3 install pycedict` but `import cedict` fails with:

```
  File "/home/astromme/.local/lib/python3.5/site-packages/cedict/__init__.py", line 1, in <module>
    from cedict_parser import iter_cedict
ImportError: No module named 'cedict_parser'
```

**Comment by kerrickstaley** [comment]
I think this is indeed because the project does not support Python 3. Maybe rename the issue title to "Support Python 3"?

**Comment by jdillworth** [comment]
Yes indeed, currently only Python 2 is supported. That will change soon.

**Comment by jdillworth** [comment]
Should work now
